import { Site } from './types';

export const initialSites: Site[] = [
  {
    id: 'partykeys',
    name: 'PartyKeys AI',
    url: 'https://partykeys.ai/',
    tags: [
      'hardware',
      'keyboard',
      'apps',
      'midi',
      'sysex',
      'open-source',
      'piano',
      'practice',
      'game',
      'chord',
    ],
    description:
      'A 36-key light-up MIDI keyboard with a universe of AI-powered music apps.',
  },
  {
    id: 'espressivo',
    name: 'Espressivo',
    url: 'https://music.ursamedia.ch/apps/espressivo/',
    tags: ['webaudio', 'piano', 'interpret', 'score', 'gamepad'],
    description:
      'Control the performance of musical scores with the help of a gamepad',
  },
  {
    id: 'amyboard',
    name: 'AMYboard Online',
    url: 'https://www.amyboard.com/editor/',
    tags: ['open-source', 'config', 'utility', 'firmware', 'webmidi', 'synth'],
    description: 'Online editor for AMYboard open-source synth module.',
    sponsor: {
      active: true,
      tier: 'supporter',
      since: '2026-06-23',
    },
  },
  {
    id: 'synth-explorer',
    name: 'Synth Explorer',
    url: 'https://synth-explorer.com',
    tags: [
      'synth',
      'analog',
      'sysex',
      'utility',
      'editor',
      'hardware',
      'librarian',
      'library',
      'oberheim',
      'sequential',
    ],
    description:
      'A browser-based editor and librarian for the Oberheim OB-6 and Sequential Prophet-6.',
  },
  {
    id: 'sightread',
    name: 'SIGHTREAD',
    url: 'https://sightread.dev/',
    tags: ['sightread', 'chord', 'training', 'piano', 'record'],
    description: 'Plug in your keyboard and learn, right in your browser',
  },
  {
    id: 'mia',
    name: 'MIA',
    url: 'https://iammia.tiiny.site/MIA.html',
    tags: ['practice', 'chord', 'training', 'piano', 'guitar'],
    description: 'Musical Instrument Assistant - Responsive Music Workspace',
  },
  {
    id: 'hexatone',
    name: 'PLAINSOUND HEXATONE',
    url: 'https://hexatone.plainsound.org',
    tags: ['synth', 'webaudio', 'lumatone', 'isomorphic', 'keyboard'],
    description:
      'A microtonal app for mapping keyboards and 2D controllers to custom tunings.',
  },
  {
    id: 'microtonal',
    name: 'microtonal',
    url: 'https://www.websynths.com/microtonal/',
    tags: ['synth', 'microtonal', 'keyboard'],
    description:
      'A microtonal web synthesizer with advanced tuning capabilities.',
  },
  {
    id: 'warbl-scala-fingering-laboratory',
    name: 'WARBL Scala Fingering Laboratory',
    url: 'https://burningcicada.github.io/warbl-scala-fingering-laboratory/',
    tags: ['controller', 'microtonal', 'webmidi', 'utility', 'training'],
    description:
      'Explore Scala tunings, design and test WARBL/WARBL2 fingering maps, audition exact microtonal pitch, and analyze expressive performance in the browser.',
  },
  {
    id: 'midi-city',
    name: 'midi.city',
    url: 'https://midi.city',
    tags: ['synth', 'keyboard', 'playback', 'sequencer'],
    description: 'A collaborative online MIDI synthesizer and sequencer.',
  },
  {
    id: 'midi-monitor',
    name: 'MIDI Monitor',
    url: 'https://www.midimonitor.com',
    tags: ['utility', 'sysex', 'monitor'],
    description:
      'A tool to monitor and analyze incoming MIDI messages in real-time.',
  },
  {
    id: 'midi-surf',
    name: 'MIDI Surf',
    url: 'https://midisurf.app',
    tags: ['controller', 'drum', 'performance'],
    description:
      'A flexible and powerful MIDI controller anywhere you have a browser!.',
  },
  {
    id: 'retrokits',
    name: 'RetroKits - Small, Smart Music Tools',
    url: 'https://retrokits.com',
    tags: ['hardware', 'sysex', 'utility', 'company'],
    description:
      'Small, Smart Music Tools with great MIDI hardware utility solutions.',
  },
  {
    id: 'noodlerack',
    name: 'NOODLERACK - Patchable Modular',
    url: 'https://noodlerack.com',
    tags: ['modular', 'eurorack', 'modules', 'synth'],
    description: 'Patchable Modular Synthesizer',
  },
  {
    id: 'ryoturia',
    name: 'ryoturia - ThreeJS Synth',
    url: 'https://ryoturia.netlify.app/',
    tags: ['synth', 'webaudio', '3d'],
    description:
      'An experimental 3D synthesizer built with Three.js and Web Audio API.',
  },
  {
    id: 'sound-fonts',
    name: 'Sound Fonts',
    url: 'https://chromatone.center/practice/synth/soundfont/',
    tags: ['synth', 'soundfont', 'playback'],
    description: 'A web-based soundfont player and synthesizer.',
  },
  {
    id: 'sr-training',
    name: 'Sight Reading Training',
    url: 'https://sightreading.training/',
    tags: ['training', 'piano', 'webaudio'],
    description:
      'a free way to practice sight reading by playing randomly generated sheet music',
  },
  {
    id: 'soundmondo',
    name: 'Soundmondo',
    url: 'https://soundmondo.yamahasynth.com/',
    tags: ['hardware', 'sysex', 'utility', 'company'],
    description:
      'Soundmondo is a social sound-sharing community for creating, sharing and exploring synthesizer sounds.',
  },
  {
    id: 'studio-code',
    name: 'Studio Code Utilities',
    url: 'https://studiocode.dev/utilities/',
    tags: ['utility', 'sysex', 'tools'],
    description: 'A collection of utilities for MIDI developers and musicians.',
  },
  {
    id: 'synthesiamaniac',
    name: 'Synthesiamaniac MIDI',
    url: 'https://synthesiamaniac.com/downloads/',
    tags: ['playback', 'midi', 'library', 'playback'],
    description: 'A large collection of MIDI files and playback tools.',
  },
  {
    id: 'tonejs',
    name: 'Tone.js Demos',
    url: 'https://tonejs.github.io/demos',
    tags: ['webaudio', 'synth', 'drums', 'library'],
    description:
      'Interactive demonstrations of the Tone.js Web Audio framework.',
  },
  {
    id: 'webmidijs',
    name: 'WebMidi.js',
    url: 'https://webmidijs.org',
    tags: ['utility', 'library', 'api'],
    description:
      'A JavaScript library that makes the Web MIDI API easier to use.',
  },
  {
    id: 'playtronica',
    name: 'Web Synths Collection',
    url: 'https://synth.playtronica.com',
    tags: ['synth', 'webaudio', 'collection'],
    description:
      'A curated collection of web-based synthesizers by Playtronica.',
  },
  {
    id: 'piano-projector',
    name: 'Piano Projector',
    url: 'https://pianoprojector.app',
    tags: ['keyboard'],
    description:
      'A versatile and easy-to-use on-screen virtual piano keyboard.',
  },
  {
    id: 'piano-trainer-studio',
    name: 'Piano Trainer Studio',
    url: 'https://pianotrainerstudio.com',
    tags: ['training', 'piano', 'midi', 'playback', 'webaudio'],
    description:
      'Interactive piano practice app with sheet music playback, MIDI input, and training modes for learning songs.',
  },
  {
    id: 'piano-ml',
    name: 'PianoML',
    url: 'https://pianoml.org',
    tags: [
      'piano',
      'score',
      'practice',
      'library',
      'omr',
      'scales',
      'sight-reading',
      'open-source',
    ],
    description:
      'A free, open-source web app to learn and practice piano with smart sheet music. Features a large and growing (12k+) personal music library enriched via MusicBrainz thesaurus and music21 musicological analysis (grade, tonality, composer, genre, hands, etc.). Offers interactive practice tools including looping, hand separation, real-time note correction, generated scales with instant MIDI feedback, and more. Supports MusicXML, MIDI, and PDF imports (with OMR).',
  },
  {
    id: 'signal',
    name: 'signal',
    url: 'https://signalmidi.app',
    tags: ['editor', 'piano', 'soundfont', 'open-source'],
    description: 'Fully Open-sourced Online MIDI Editor',
  },
  {
    id: 'Pilot',
    name: 'Pilot',
    url: 'https://vl3x.info',
    tags: ['synth', 'webaudio'],
    description: 'Pilot is for TC Helicon VoiceLive 3 and VoiceLive 3 Extreme.',
  },
  {
    id: 'play-drums-online',
    name: 'PlayDrumsOnline',
    url: 'https://www.playdrumsonline.com',
    tags: [
      'drum',
      'midi',
      'training',
      'practice',
      'sheet-music',
      'transcription',
      'sequencer',
    ],
    description:
      'Practice drums in the browser with 2000+ songs as drum sheet or rhythm game. AI-generated transcription from MP3/YouTube, MIDI input from electronic kits, real-time scoring, sheet editor, and PDF/MIDI export.',
    sponsor: {
      active: true,
      tier: 'supporter',
      since: '2026-05-11',
    },
  },
  {
    id: 'midipiano',
    name: 'midipiano.app',
    url: 'https://midipiano.app',
    tags: [
      'piano',
      'midi',
      'practice',
      'sightread',
      'score',
      'training',
      'webaudio',
    ],
    description:
      'Practice piano in your browser: connect a MIDI keyboard, import MusicXML or MEI scores, and get real-time per-hand feedback.',
  },
  {
    id: 'ultimate-piano',
    name: 'The Ultimate Piano',
    url: 'https://app.the-ultimate-piano.com/',
    tags: [
      'piano',
      'practice',
      'training',
      'chord',
      'scales',
      'score',
      'sheet-music',
      'sight-reading',
      'webmidi',
    ],
    sponsor: {
      active: true,
      tier: 'supporter',
      since: '2026-08-01',
    },
    description:
      'Piano practice workspace: live notation and chord detection from your MIDI keyboard, plus sheet-music playback, scale and chord drills, and ear training.',
  },
  {
    id: 'zoom-l6-companion',
    name: 'Zoom L6 Companion',
    url: 'https://zooml6.webmidi.cc',
    tags: [
      'hardware',
      'mixer',
      'controller',
      'utility',
      'editor',
      'open-source',
      'midi',
      'webmidi',
    ],
    description:
      'A WebMIDI companion for the Zoom LiveTrak L6 and L6Max with channel strips, EQ, LFOs, sound pads, and customizable MIDI CC mappings.',
  },
  {
    id: 'workshop-turing-machine',
    name: 'Turing Machine Editor',
    url: 'https://tomwhitwell.github.io/Turing_Machine_Workshop_Computer/',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'sequencer',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI SysEx editor for the Music Thing Workshop Computer Turing Machine card: scales, pulse modes, ranges, and two switch presets.',
  },
  {
    id: 'workshop-usb-audio',
    name: 'Workshop USB Bridge Config',
    url: 'https://vincentmaurer.de/usb-audio/midi_config.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'utility',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI editor for the Workshop Computer USB Audio & MIDI card: sample rate, channel routing, and CV/gate mapping stored to flash.',
  },
  {
    id: 'workshop-reverb-plus',
    name: 'Reverb+ Editor',
    url: 'https://www.musicthing.co.uk/web_config/reverb.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI config editor for Reverb+ on the Workshop Computer: reverb routing plus MIDI-to-CV, clocks, Turing, and Bernoulli utilities.',
  },
  {
    id: 'workshop-clockwork',
    name: 'Clockwork Web MIDI Manager',
    url: 'https://vincentmaurer.de/clockwork/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'sequencer',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI manager for the Workshop Computer Clockwork card: per-channel clock math, Euclidean patterns, output shapes, and live telemetry.',
  },
  {
    id: 'workshop-drumdrum',
    name: 'drumdrum WebMIDI Editor',
    url: 'https://mohoyt.com/drumdrum.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'sequencer',
      'drum',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI SysEx editor for the Workshop Computer drumdrum card, a DFAM-style 8-step pitch and velocity sequencer.',
  },
  {
    id: 'workshop-flux',
    name: 'Flux Manager',
    url: 'https://vincentmaurer.de/flux/flux_manager.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'librarian',
      'synth',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI sample manager, patch sharing, and routing editor for the Workshop Computer Flux card.',
  },
  {
    id: 'workshop-zx',
    name: 'ZX Workshop Computer Web UI',
    url: 'https://uglifruit.github.io/WorkshopZX/interface.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'utility',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI SysEx UI for the Workshop Computer ZX card: snapshot and chip-music upload plus jack-to-key remapping.',
  },
  {
    id: 'workshop-biomimicry',
    name: 'BioMimicry Sample Uploader',
    url: 'https://computer.musicthing.co.uk/programs/62-biomimicry/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'librarian',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI sample uploader and slot mapper for the Workshop Computer BioMimicry card.',
  },
  {
    id: 'workshop-fragments',
    name: 'Fragments Web Editor',
    url: 'https://computer.musicthing.co.uk/programs/67-fragments/web/fragments_librarian.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'librarian',
      'sequencer',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI librarian for the Workshop Computer Fragments sampler: kits, samples, patterns, and CV output config.',
  },
  {
    id: 'workshop-computer-grids',
    name: 'Computer Grids Config',
    url: 'https://computer.musicthing.co.uk/programs/82-computer-grids/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'sequencer',
      'drum',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI SysEx config editor for the Workshop Computer Grids-inspired trigger sequencer card.',
  },
  {
    id: 'workshop-cosmik-c1zzl3',
    name: 'C1ZZL3 Envelope Lab (Cosmik)',
    url: 'https://computer.musicthing.co.uk/programs/84-cosmikc1zzl3/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'synth',
      'librarian',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI envelope, phase-distortion, and sound-preset editor for Cosmik C1ZZL3 on the Workshop Computer.',
  },
  {
    id: 'workshop-fr330hfr33',
    name: 'Fr330hfr33 Editor',
    url: 'https://computer.musicthing.co.uk/programs/87-fr330hfr33/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'synth',
      'sequencer',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI editor for the Workshop Computer Fr330hfr33 acid voice: filter, distortion, and a persistent 16-step sequencer.',
  },
  {
    id: 'workshop-turing-matrix',
    name: 'Turing Matrix Web Config',
    url: 'https://computer.musicthing.co.uk/programs/93-turing-matrix/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'config',
      'sequencer',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI SysEx editor for the Workshop Computer Turing Matrix card: Turing layer settings plus mixer-layer config.',
  },
  {
    id: 'workshop-gnarly-c1zzl3',
    name: 'C1ZZL3 Envelope Lab (Gnarly)',
    url: 'https://computer.musicthing.co.uk/programs/101-gnarly-c1zzl3/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'synth',
      'librarian',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI envelope, phase-distortion, and named sound-preset editor for Gnarly C1ZZL3 on the Workshop Computer.',
  },
  {
    id: 'workshop-nibble-ko',
    name: 'NIBBLE-KO Setup',
    url: 'https://computer.musicthing.co.uk/programs/102-nibble-ko/web/index.html',
    tags: [
      'hardware',
      'editor',
      'sysex',
      'librarian',
      'drum',
      'synth',
      'webmidi',
      'modular',
      'music-thing',
      'workshop-system-computer',
    ],
    description:
      'Web MIDI sample library and kit assignment editor for the Workshop Computer NIBBLE-KO percussion looper.',
  },
];

export const allTags = Array.from(
  new Set(initialSites.flatMap((site) => site.tags)),
).sort();
